#!bin/bash 

# Make directory with parents
alias mkdir='mkdir -p'
alias vim='nvim'
alias vi='nvim'
alias nv='nvim'
alias ping='ping -c 10'
alias cls='clear'
alias cd..='cd ..'
alias ls='ls -lh --color=auto'
alias ll='ls -alh --color=auto' 
# alias brave-browser="brave-browser --enable-features=VaapiVideoDecodeLinuxGL"
